export const SETTINGS_MENU_ITEMS = {
  ACCOUNT: "ACCOUNT",
  DISCUSSION: "DISCUSSION",
  FILE: "FILE",
  DEVICE: "DEVICE",
  POST: "POST",
  TASK: "TASK",
  OUT_OF_THE_OFFICE_POLICY: "OUT_OF_THE_OFFICE_POLICY",
  NOTIFICATION: "NOTIFICATION",
  PRESET: "PRESET",
};
