export const taskConstants = {
  TODO: "TODO",
  ASSIGN: "ASSIGN",
  INPROGRESS: "INPROGRESS",
  REQUESTAPPROVAL: "REQUESTAPPROVAL",
  APPROVED: "APPROVED",
  DONE: "DONE",
  PENDING: "PENDING",
  CANCELED: "CANCELED",
};
