const ChannelType = {
  INTERNAL_CHANNEL: "INTERNAL_CHANNEL",
  EXTERNAL_CHANNEL: "EXTERNAL_CHANNEL",
  GUEST_CHANNEL: "GUEST_CHANNEL",
  DIRECT_CHANNEL: "DIRECT_CHANNEL",
};
export default ChannelType;
