const FETCH_CHANNEL_DETAILS = Symbol("FETCH_CHANNEL_DETAILS");
const FETCH_CHANNEL_DETAILS_SUCCESS = Symbol("FETCH_CHANNEL_DETAILS_SUCCESS");
const FETCH_CHANNEL_DETAILS_ERROR = Symbol("FETCH_CHANNEL_DETAILS_ERROR");
const UPDATE_CHANNEL_LAST_POST = Symbol("UPDATE_CHANNEL_LAST_POST");

const FETCH_CHANNEL_MEMBERS = Symbol("FETCH_CHANNEL_MEMBERS");
const FETCH_CHANNEL_MEMBERS_SUCCESS = Symbol("FETCH_CHANNEL_MEMBERS_SUCCESS");
const FETCH_CHANNEL_MEMBERS_ERROR = Symbol("FETCH_CHANNEL_MEMBERS_ERROR");

const FETCH_ALL_CHANNEL_MEMBERS = Symbol("FETCH_ALL_CHANNEL_MEMBERS");
const FETCH_ALL_CHANNEL_MEMBERS_SUCCESS = Symbol(
  "FETCH_ALL_CHANNEL_MEMBERS_SUCCESS"
);
const FETCH_ALL_CHANNEL_MEMBERS_ERROR = Symbol(
  "FETCH_ALL_CHANNEL_MEMBERS_ERROR"
);

const FETCH_USERS_PROFILE_IMAGE = Symbol("FETCH_USERS_PROFILE_IMAGE");
const FETCH_USERS_PROFILE_IMAGE_SUCCESS = Symbol(
  "FETCH_USERS_PROFILE_IMAGE_SUCCESS"
);
const FETCH_USERS_PROFILE_IMAGE_ERROR = Symbol(
  "FETCH_USERS_PROFILE_IMAGE_ERROR"
);

const GET_CHANNEL_MEMBERS = Symbol("GET_CHANNEL_MEMBERS");
const GET_CHANNEL_MEMBERS_SUCCESS = Symbol("GET_CHANNEL_MEMBERS_SUCCESS");
const GET_CHANNEL_MEMBERS_ERROR = Symbol("GET_CHANNEL_MEMBERS_ERROR");

const FETCH_USER_TYPE = Symbol("FETCH_USER_TYPE");
const FETCH_USER_TYPE_ERROR = Symbol("FETCH_USER_TYPE_ERROR");
const FETCH_USER_TYPE_SUCCESS = Symbol("CHANNEL_USER_TYPE_SUCCESS");
const RESET_USER_TYPE = Symbol("RESET_USER_TYPE");
const UPDATE_CHANNEL_MESSAGE_COUNT = Symbol("UPDATE_CHANNEL_MESSAGE_COUNT");

const FETCH_USER_DETAILS = Symbol("FETCH_USER_DETAILS");
const FETCH_USER_DETAILS_SUCCESS = Symbol("FETCH_USER_DETAILS_SUCCESS");
const FETCH_USER_DETAILS_ERROR = Symbol("FETCH_USER_DETAILS_ERROR");
const CHANNEL_USER_REMOVED = Symbol("CHANNEL_USER_REMOVED");

const REMOVE_CHANNEL_MEMBER = Symbol("REMOVE_CHANNEL_MEMBER");
const REMOVE_CHANNEL_MEMBER_SUCCESS = Symbol("REMOVE_CHANNEL_MEMBER_SUCCESS");
const REMOVE_CHANNEL_MEMBER_ERROR = Symbol("REMOVE_CHANNEL_MEMBER_ERROR");
const REMOVE_CHANNEL_MEMBER_RESET = Symbol("REMOVE_CHANNEL_MEMBER_RESET");

const CREATE_CHANNEL_REQUEST = Symbol("CREATE_CHANNEL_REQUEST");
const CREATE_CHANNEL_SUCCESS = Symbol("CREATE_CHANNEL_SUCCESS");
const CREATE_CHANNEL_ERROR = Symbol("CREATE_CHANNEL_ERROR");
const CREATE_CHANNEL_RESET = Symbol("CREATE_CHANNEL_RESET");

const FETCH_CHANNEL_LIST_REQUEST = Symbol("FETCH_CHANNEL_LIST_REQUEST");
const FETCH_CHANNEL_LIST_SUCCESS = Symbol("FETCH_CHANNEL_LIST_SUCCESS");
const FETCH_CHANNEL_LIST_ERROR = Symbol("FETCH_CHANNEL_LIST_ERROR");
const UPDATE_CHANNEL_POST_READ_AT = Symbol("UPDATE_CHANNEL_POST_READ_AT");

const SYNC_CHANNEL_MESSAGES = Symbol("SYNC_CHANNEL_MESSAGES");

const LEAVE_CHANNEL = Symbol("LEAVE_CHANNEL");
const LEAVE_CHANNEL_SUCCESS = Symbol("LEAVE_CHANNEL_SUCCESS");
const LEAVE_CHANNEL_ERROR = Symbol("LEAVE_CHANNEL_ERROR");

const RENAME_CHANNEL = Symbol("RENAME_CHANNEL");
const RENAME_CHANNEL_SUCCESS = Symbol("RENAME_CHANNEL_SUCCESS");
const RENAME_CHANNEL_ERROR = Symbol("RENAME_CHANNEL_ERROR");

const DELETE_CHANNEL = Symbol("DELETE_CHANNEL");
const DELETE_CHANNEL_SUCCESS = Symbol("DELETE_CHANNEL_SUCCESS");
const DELETE_CHANNEL_ERROR = Symbol("DELETE_CHANNEL_ERROR");

const RESET_CONTROL_FLAGS = Symbol("RESET_CONTROL_FLAGS");

const INITIATED_DISCUSSION_DELETE = Symbol("INITIATED_DISCUSSION_DELETE");
const COMPLETED_DISCUSSION_DELETE = Symbol("COMPLETED_DISCUSSION_DELETE");

const INITIATED_DISCUSSION_ARCHIVE = Symbol("INITIATED_DISCUSSION_ARCHIVE");
const COMPLETED_DISCUSSION_ARCHIVE = Symbol("COMPLETED_DISCUSSION_ARCHIVE");
const ARCHIVE_CHANNEL = Symbol("ARCHIVE_CHANNEL");
const ARCHIVE_CHANNEL_SUCCESS = Symbol("ARCHIVE_CHANNEL_SUCCESS");
const ARCHIVE_CHANNEL_ERROR = Symbol("ARCHIVE_CHANNEL_ERROR");

const DELETION_STATUS = Symbol("DELETION_STATUS");
const DELETION_STATUS_SUCCESS = Symbol("DELETION_STATUS_SUCCESS");
const DELETION_STATUS_ERROR = Symbol("DELETION_STATUS_ERROR");
const RESET_NEW_CHANNEL = Symbol("RESET_NEW_CHANNEL");
const UPDATE_CHANNEL_NOTIFICATION_FILTER = Symbol(
  "UPDATE_CHANNEL_NOTIFICATION_FILTER"
);

const DISCUSSION_NOTIFICATION_FILTER_UPDATE = Symbol(
  "DISCUSSION_NOTIFICATION_FILTER_UPDATE"
);
const DISCUSSION_NOTIFICATION_FILTER_UPDATE_SUCCESS = Symbol(
  "DISCUSSION_NOTIFICATION_FILTER_UPDATE_SUCCESS"
);
const DISCUSSION_NOTIFICATION_FILTER_UPDATE_FAILURE = Symbol(
  "DISCUSSION_NOTIFICATION_FILTER_UPDATE_FAILURE"
);

const FETCH_POST_SEARCH_LIST_SUCCESS = Symbol("FETCH_POST_SEARCH_LIST_SUCCESS");
const FETCH_POST_SEARCH_LIST_REQUEST = Symbol("FETCH_POST_SEARCH_LIST_REQUEST");
const FETCH_POST_SEARCH_LIST_ERROR = Symbol("FETCH_POST_SEARCH_LIST_ERROR");

const FETCH_POST_SEARCH_DETAILS_SUCCESS = Symbol(
  "FETCH_POST_SEARCH_DETAILS_SUCCESS"
);
const FETCH_POST_SEARCH_DETAILS_ERROR = Symbol(
  "FETCH_POST_SEARCH_DETAILS_ERROR"
);
const FETCH_POST_SEARCH_DETAILS_REQUEST = Symbol(
  "FETCH_POST_SEARCH_DETAILS_REQUEST"
);

const FETCH_POST_SEARCH_DETAILS_CLEAR = Symbol(
  "FETCH_POST_SEARCH_DETAILS_CLEAR"
);
const POST_SEARCH = Symbol("POST_SEARCH");
const UPDATE_LAST_SEARCH_QUERY = Symbol("UPDATE_LAST_SEARCH_QUERY");
const UPDATE_CHANNEL_CREATOR = Symbol("UPDATE_CHANNEL_CREATOR");
const UPDATE_CHANNEL_MESSAGES_DATA = Symbol("UPDATE_CHANNEL_MESSAGES_DATA");
const UPDATE_DISCUSSION_LAST_READ_POST_ID = Symbol(
  "UPDATE_DISCUSSION_LAST_READ_POST_ID"
);
const UPDATE_CHANNEL_LIST_LAST_POST = Symbol("UPDATE_CHANNEL_LIST_LAST_POST");
const RESET_NEW_UNREAD_MESSAGE_COUNT = Symbol("RESET_NEW_UNREAD_MESSAGE_COUNT");
export {
  FETCH_USER_TYPE,
  FETCH_POST_SEARCH_LIST_SUCCESS,
  FETCH_POST_SEARCH_LIST_REQUEST,
  FETCH_POST_SEARCH_LIST_ERROR,
  FETCH_USER_TYPE_ERROR,
  FETCH_POST_SEARCH_DETAILS_SUCCESS,
  FETCH_POST_SEARCH_DETAILS_ERROR,
  FETCH_POST_SEARCH_DETAILS_REQUEST,
  FETCH_POST_SEARCH_DETAILS_CLEAR,
  FETCH_USER_TYPE_SUCCESS,
  RESET_USER_TYPE,
  POST_SEARCH,
  FETCH_CHANNEL_DETAILS,
  FETCH_CHANNEL_DETAILS_SUCCESS,
  FETCH_CHANNEL_DETAILS_ERROR,
  UPDATE_CHANNEL_LAST_POST,
  FETCH_CHANNEL_MEMBERS,
  FETCH_CHANNEL_MEMBERS_SUCCESS,
  FETCH_CHANNEL_MEMBERS_ERROR,
  FETCH_ALL_CHANNEL_MEMBERS,
  FETCH_ALL_CHANNEL_MEMBERS_SUCCESS,
  FETCH_ALL_CHANNEL_MEMBERS_ERROR,
  GET_CHANNEL_MEMBERS,
  GET_CHANNEL_MEMBERS_SUCCESS,
  GET_CHANNEL_MEMBERS_ERROR,
  FETCH_USER_DETAILS,
  FETCH_USER_DETAILS_SUCCESS,
  FETCH_USER_DETAILS_ERROR,
  CHANNEL_USER_REMOVED,
  REMOVE_CHANNEL_MEMBER,
  REMOVE_CHANNEL_MEMBER_SUCCESS,
  REMOVE_CHANNEL_MEMBER_ERROR,
  REMOVE_CHANNEL_MEMBER_RESET,
  CREATE_CHANNEL_REQUEST,
  CREATE_CHANNEL_SUCCESS,
  CREATE_CHANNEL_ERROR,
  CREATE_CHANNEL_RESET,
  FETCH_CHANNEL_LIST_REQUEST,
  FETCH_CHANNEL_LIST_SUCCESS,
  FETCH_CHANNEL_LIST_ERROR,
  UPDATE_CHANNEL_POST_READ_AT,
  SYNC_CHANNEL_MESSAGES,
  UPDATE_CHANNEL_MESSAGE_COUNT,
  LEAVE_CHANNEL,
  LEAVE_CHANNEL_SUCCESS,
  LEAVE_CHANNEL_ERROR,
  RENAME_CHANNEL,
  RENAME_CHANNEL_SUCCESS,
  RENAME_CHANNEL_ERROR,
  DELETE_CHANNEL,
  DELETE_CHANNEL_SUCCESS,
  DELETE_CHANNEL_ERROR,
  RESET_CONTROL_FLAGS,
  INITIATED_DISCUSSION_DELETE,
  COMPLETED_DISCUSSION_DELETE,
  INITIATED_DISCUSSION_ARCHIVE,
  COMPLETED_DISCUSSION_ARCHIVE,
  ARCHIVE_CHANNEL,
  ARCHIVE_CHANNEL_SUCCESS,
  ARCHIVE_CHANNEL_ERROR,
  DELETION_STATUS,
  DELETION_STATUS_SUCCESS,
  DELETION_STATUS_ERROR,
  RESET_NEW_CHANNEL,
  DISCUSSION_NOTIFICATION_FILTER_UPDATE,
  DISCUSSION_NOTIFICATION_FILTER_UPDATE_SUCCESS,
  DISCUSSION_NOTIFICATION_FILTER_UPDATE_FAILURE,
  UPDATE_CHANNEL_NOTIFICATION_FILTER,
  UPDATE_LAST_SEARCH_QUERY,
  UPDATE_CHANNEL_CREATOR,
  UPDATE_CHANNEL_MESSAGES_DATA,
  UPDATE_DISCUSSION_LAST_READ_POST_ID,
  UPDATE_CHANNEL_LIST_LAST_POST,
  FETCH_USERS_PROFILE_IMAGE,
  FETCH_USERS_PROFILE_IMAGE_SUCCESS,
  FETCH_USERS_PROFILE_IMAGE_ERROR,
  RESET_NEW_UNREAD_MESSAGE_COUNT,
};
