export const GET_COLLECTION_DATA = Symbol("GET_COLLECTION_DATA");
export const UPDATE_COLLECTION_DATA = Symbol("UPDATE_COLLECTION_DATA");
export const SET_NOTIFICATIONS_WS = Symbol("SET_NOTIFICATIONS_WS");

export const SET_ACTIVE_COLLECTION = Symbol("SET_ACTIVE_COLLECTION");
