export const FETCH_POST_REPLY = Symbol("FETCH_POST_REPLY");
export const FETCH_POST_REPLY_SUCCESS = Symbol("FETCH_POST_REPLY_SUCCESS");
export const FETCH_POST_REPLY_ERROR = Symbol("FETCH_POST_REPLY_ERROR");
export const CLEAR_MESSAGES_REPLY_POST = Symbol("CLEAR_MESSAGES_REPLY_POST");
export const LOAD_POST_REPLY = Symbol("LOAD_POST_REPLY");
export const LOAD_POST_REPLY_SUCCESS = Symbol("LOAD_POST_REPLY_SUCCESS");
export const LOAD_POST_REPLY_ERROR = Symbol("LOAD_POST_REPLY_ERROR");
export const FETCH_EMBEDDED_LINK_REQUEST_REPLY = Symbol(
  "FETCH_EMBEDDED_LINK_REQUEST_REPLY"
);
export const FETCH_EMBEDDED_LINK_SUCCESS_REPLY = Symbol(
  "FETCH_EMBEDDED_LINK_SUCCESS_REPLY"
);
export const FETCH_EMBEDDED_LINK_ERROR_REPLY = Symbol(
  "FETCH_EMBEDDED_LINK_ERROR_REPLY"
);
export const UPDATE_FILE_INFO_STATS_REPLY = Symbol(
  "UPDATE_FILE_INFO_STATS_REPLY"
);
export const UPDATE_REPLY_FILE_INFO = Symbol("UPDATE_REPLY_FILE_INFO");
export const UPDATE_CURRENT_SELECTED_PARENT_POST = Symbol(
  "UPDATE_CURRENT_SELECTED_PARENT_POST"
);
export const CLEAR_MESSAGES_REPLY_POST_FOR_PARENT = Symbol(
  "CLEAR_MESSAGES_REPLY_POST_FOR_PARENT"
);
