const Panel = {
  CHANNEL: "CHANNEL",
  OUTLOOK_EMAIL: "OUTLOOK_EMAIL",
  JOIN_DISCUSSION_AGREEMENT: "JOIN_DISCUSSION_AGREEMENT",
  NEW_DISCUSSION: "NEW_DISCUSSION",
  WELCOME: "WELCOME",
  WELCOME_EMAIL: "WELCOME_EMAIL",
};
export default Panel;
