/*
 *Constants to be used for API RESPONSE codes
 */
const StatusCode = {
  LOGIN_SUCCESS: "",
  LOGIN_FAIL_USERNAME: 4006,
  LOGIN_FAIL_PASSWORD: 4007,
  LOGIN_FAIL_USERNAME_PASSWORD: 4008,

  SIGNUP_SUCCESS: "",
  SIGNUP_FAIL_UID: 4004,
  SIGNUP_FAIL_EMAIL: 4005,

  REGISTER_SUCCESS: "",
  REGISTER_FAIL: "",

  SCREEN_NAME_SUCCESS: 2005,
  SCREEN_NAME_FAIL: 4009,

  RESEND_EMAIL_SUCCESS: "",
  RESEND_EMAIL_FAIL: 4007,

  RESET_REQUEST_SUCCESS: 2002,
  RESET_REQUEST_FAIL_EMAIL: 4401,

  UPDATE_PASSWORD_SUCCESS: 2004,
  UPDATE_REQUEST_FAIL_EMAIL: 5001,

  COMMON_ERROR: 4001,
  NAME_TAKEN: 4011,
  SERVER_ERROR: 5001,
  COMMON_SUCCESS: 2001,
  COLLECTION_ACTION_SUCCESS: 40027,
  COLLECTION_ACTION_ERROR: 40026
};

export default StatusCode;
