export const SET_ACTIVE_PANEL = Symbol("SET_ACTIVE_PANEL");
export const SET_SELECTED_CHANNEL = Symbol("SET_SELECTED_CHANNEL");
export const UPDATE_CHANNEL_NAME = Symbol("UPDATE_CHANNEL_NAME");
export const SET_REDIRECT_POST_ID = Symbol("SET_REDIRECT_POST_ID");
export const RESET_REDIRECT_POST_ID = Symbol("RESET_REDIRECT_POST_ID");
export const SET_REDIRECT_POST_ICON_VISIBLE = Symbol(
  "SET_REDIRECT_POST_ICON_VISIBLE"
);
export const RESET_REDIRECT_POST_ICON_VISIBLE = Symbol(
  "RESET_REDIRECT_POST_ICON_VISIBLE"
);
export const FETCH_FILE_CONFIG_REQUEST = Symbol("FETCH_FILE_CONFIG_REQUEST");
export const FETCH_FILE_CONFIG_SUCCESS = Symbol("FETCH_FILE_CONFIG_SUCCESS");
export const FETCH_FILE_CONFIG_ERROR = Symbol("FETCH_FILE_CONFIG_ERROR");
export const SUMMARY_PANEL_ACTIVE_STATE = Symbol("SUMMARY_PANEL_ACTIVE_STATE");
export const SUMMARY_PANEL_ACTIVE_INDEX = Symbol("SUMMARY_PANEL_ACTIVE_INDEX");
export const FETCH_APP_VERSION = Symbol("FETCH_APP_VERSION");
export const FETCH_APP_VERSION_SUCCESS = Symbol("FETCH_APP_VERSION_SUCCESS");
export const FETCH_APP_VERSION_FAILURE = Symbol("FETCH_APP_VERSION_FAILURE");
export const UPDATE_APP_VERSION = Symbol("UPDATE_APP_VERSION");
export const UPDATE_USER_TYPING_STATUS = Symbol("UPDATE_USER_TYPING_STATUS");
export const SET_ACTIVE_MENU_ITEM = Symbol("SET_ACTIVE_MENU_ITEM");
export const SET_ACTIVE_FILE_MENU_ITEM = Symbol("SET_ACTIVE_FILE_MENU_ITEM");
export const SET_ACTIVE_SETTING_MENU_ITEM = Symbol(
  "SET_ACTIVE_SETTING_MENU_ITEM"
);
export const SET_SELECTED_FILE = Symbol("SET_SELECTED_FILE");
export const FILE_PANEL_ACTIVE_STATE = Symbol("FILE_PANEL_ACTIVE_STATE");
export const ADMIN_SIDEBAR_SELECTED_PANEL = Symbol(
  "ADMIN_SIDEBAR_SELECTED_PANEL"
);
export const ADMIN_SIDEBAR_ACTIVE_STATE = Symbol("ADMIN_SIDEBAR_ACTIVE_STATE");
export const ADMIN_SIDEBAR_SELECTED_INDEX = Symbol(
  "ADMIN_SIDEBAR_SELECTED_INDEX"
);
